/**
 * Folder domain constants
 * Error codes and messages specific to the Folder domain
 */

export const FOLDER_ERROR_CODES = {
  NOT_FOUND: "FOLDER_NOT_FOUND",
  CREATE_FAILED: "FOLDER_CREATE_FAILED",
  UPDATE_FAILED: "FOLDER_UPDATE_FAILED",
  DELETE_FAILED: "FOLDER_DELETE_FAILED",
  INVALID_ID: "FOLDER_INVALID_ID",
  INVALID_NAME: "FOLDER_INVALID_NAME",
  INVALID_PARENT: "FOLDER_INVALID_PARENT",
  PARENT_NOT_FOLDER: "FOLDER_PARENT_NOT_FOLDER",
  NOT_DELETED: "FOLDER_NOT_DELETED",
} as const;

export const FOLDER_ERROR_MESSAGES = {
  [FOLDER_ERROR_CODES.NOT_FOUND]: "Folder not found",
  [FOLDER_ERROR_CODES.CREATE_FAILED]: "Failed to create folder",
  [FOLDER_ERROR_CODES.UPDATE_FAILED]: "Failed to update folder",
  [FOLDER_ERROR_CODES.DELETE_FAILED]: "Failed to delete folder",
  [FOLDER_ERROR_CODES.INVALID_ID]: "Invalid folder ID",
  [FOLDER_ERROR_CODES.INVALID_NAME]: "Folder name is required",
  [FOLDER_ERROR_CODES.INVALID_PARENT]: "Parent folder not found",
  [FOLDER_ERROR_CODES.PARENT_NOT_FOLDER]: "Parent must be a folder",
  [FOLDER_ERROR_CODES.NOT_DELETED]: "Folder is not deleted",
} as const;

export const FOLDER_DEFAULTS = {
  IS_FOLDER: true,
  SEARCH_LIMIT: 50,
} as const;

// Backward compatibility - will be deprecated
export const ERROR_MESSAGES = {
  FOLDER_NOT_FOUND: FOLDER_ERROR_MESSAGES[FOLDER_ERROR_CODES.NOT_FOUND],
  FAILED_TO_CREATE: FOLDER_ERROR_MESSAGES[FOLDER_ERROR_CODES.CREATE_FAILED],
  FAILED_TO_UPDATE: FOLDER_ERROR_MESSAGES[FOLDER_ERROR_CODES.UPDATE_FAILED],
  FAILED_TO_DELETE: FOLDER_ERROR_MESSAGES[FOLDER_ERROR_CODES.DELETE_FAILED],
  INVALID_ID: FOLDER_ERROR_MESSAGES[FOLDER_ERROR_CODES.INVALID_ID],
  INVALID_NAME: FOLDER_ERROR_MESSAGES[FOLDER_ERROR_CODES.INVALID_NAME],
  SEARCH_QUERY_EMPTY: "Search query cannot be empty",
} as const;

export const MAX_SEARCH_RESULTS = 50;
export const MAX_QUERY_LIMIT = 1000; // Hard limit to prevent resource exhaustion
export const DEFAULT_PAGE_SIZE = 20;
